function cfg = caddis_common_config()
% CADDIS_COMMON_CONFIG  Settings shared by all cADDis figure datasets.

%% Raw parquet layout
cfg.source_column_order = [13, 1:12];
cfg.clean_column_names = { ...
    'Time', ...
    'cADDisRaw', ...
    'mCherryRaw', ...
    'cADDisRawFit', ...
    'mCherryRawFit', ...
    'cADDisDeltaF', ...
    'mCherryDeltaF', ...
    'cADDisDFF', ...
    'mCherryDFF', ...
    'cADDisDFFFit', ...
    'mCherrySimultaneous', ...
    'cADDisDifference', ...
    'cADDisZScore'};

%% dF/F and smoothing settings
cfg.time_column_candidates = {'Time', 'time'};
cfg.signal_column_candidates = { ...
    'cADDisRaw', 'cADDis raw', 'cADDis_raw', 'cADDis', ...
    '465', 'sig', 'signal'};
cfg.reference_column_candidates = { ...
    'mCherrySimultaneous', 'mCherry_simultaneous', 'mCherry', ...
    'mCherryRaw', 'mCherry raw', 'mCherry_sim', '560', 'ref'};

cfg.canonical_start_min = -30;
cfg.baseline_window_min = [-15, 0];
cfg.safe_floor_relative = 1e-6;
cfg.smoothing_mode = 'causal';
cfg.smoothing_window_sec = 60;

% Time-based equivalent of the row ranges used in the original summaries.
cfg.section_mean_intervals_min = [-10, 0; 5, 15; 20, 30];
cfg.section_mean_labels = {'Baseline', 'T1', 'T2'};
cfg.reverse_summary_y_axis = true;
end
