function summary = summarize_extfig6c_exrai(cfg)
% SUMMARIZE_EXTFIG6C_EXRAI  Summarize RV traces in 10-minute bins.
%
% The input traces are the RV-normalized RV sessions generated by the
% shared Fig. 3f/k ExRaiAKAR2 preprocessing and normalization workflow.

treatment = cfg.analysis.treatment;
intervals = cfg.analysis.intervals;
interval_labels = cfg.analysis.labels;
CARRY_FORWARD_TAIL = cfg.analysis.carry_forward_tail;

out_dir = fullfile(cfg.summary_root,'RV_10min');
if ~exist(out_dir,'dir'), mkdir(out_dir); end

%% Per-subject numerical summary
n_intervals = size(intervals,1);
rows = cell(numel(cfg.subjects),1 + 4*n_intervals);

for s = 1:numel(cfg.subjects)
    subject = cfg.subjects{s};
    input_file = fullfile(cfg.processed_root,treatment,subject, ...
        sprintf('%s_%s_normalized_to_RV.mat',treatment,subject));

    fprintf('%s | %s\n',treatment,subject);

    if ~isfile(input_file)
        warning('Missing normalized file: %s',input_file);
        rows(s,:) = [{subject},repmat({NaN},1,4*n_intervals)];
        continue;
    end

    S = load(input_file,'t','scaled_dRR');
    if ~isfield(S,'t') || ~isfield(S,'scaled_dRR')
        warning('Missing t or scaled_dRR in %s',input_file);
        rows(s,:) = [{subject},repmat({NaN},1,4*n_intervals)];
        continue;
    end

    t = S.t(:);
    y = S.scaled_dRR(:);
    n = min(numel(t),numel(y));
    t = t(1:n);
    y = y(1:n);

    means = nan(1,n_intervals);
    auc_total = nan(1,n_intervals);
    auc_neg = nan(1,n_intervals);
    auc_pos = nan(1,n_intervals);

    for k = 1:n_intervals
        [means(k),auc_total(k),auc_neg(k),auc_pos(k)] = ...
            analyse_interval(t,y,intervals(k,:),CARRY_FORWARD_TAIL);
    end

    rows(s,:) = [{subject},num2cell(means),num2cell(auc_total), ...
        num2cell(auc_neg),num2cell(auc_pos)];
end

variable_names = {'Subject'};
variable_names = [variable_names, ...
    strcat('Mean_',interval_labels), ...
    strcat('AUC_',interval_labels), ...
    strcat('AUCneg_',interval_labels), ...
    strcat('AUCpos_',interval_labels)];

T_subject = cell2table(rows,'VariableNames',variable_names);
writetable(T_subject,fullfile(out_dir,'RV_10min_by_subject.csv'));

%% Group summary
sem = @(x) std(x,'omitnan') ./ sqrt(sum(isfinite(x)));
group_rows = cell(n_intervals,6);

for k = 1:n_intervals
    label = interval_labels{k};
    total_values = T_subject.(['AUC_' label]);
    positive_values = T_subject.(['AUCpos_' label]);

    group_rows(k,:) = { ...
        label, ...
        mean(total_values,'omitnan'), ...
        sem(total_values), ...
        mean(positive_values,'omitnan'), ...
        sem(positive_values), ...
        sum(isfinite(total_values) | isfinite(positive_values))};
end

T_group = cell2table(group_rows,'VariableNames', { ...
    'Interval','Mean_AUC','SEM_AUC','Mean_AUCpos','SEM_AUCpos','N_Subjects'});
writetable(T_group,fullfile(out_dir,'RV_10min_group_summary.csv'));

positive_columns = strcat('AUCpos_',interval_labels);
T_positive = T_subject(:,[{'Subject'},positive_columns]);
writetable(T_positive,fullfile(out_dir,'RV_positive_auc_by_subject.csv'));

save(fullfile(out_dir,'RV_10min_analysis.mat'), ...
    'T_subject','T_group','T_positive','intervals', ...
    'interval_labels','CARRY_FORWARD_TAIL');

%% Trace figure and source-data exports
fig = figure('Visible','off','Color','w', ...
    'Units','inches','Position',[1 1 4.2 3.6]);
ax = axes(fig);
hold(ax,'on');
box(ax,'off');

Y = [];
Tref = [];

for s = 1:numel(cfg.subjects)
    subject = cfg.subjects{s};
    input_file = fullfile(cfg.processed_root,treatment,subject, ...
        sprintf('%s_%s_normalized_to_RV.mat',treatment,subject));
    if ~isfile(input_file), continue; end

    S = load(input_file,'t','scaled_dRR');
    if ~isfield(S,'t') || ~isfield(S,'scaled_dRR'), continue; end

    src_t = S.t(:);
    src_y = S.scaled_dRR(:);
    valid = isfinite(src_t) & isfinite(src_y);
    src_t = src_t(valid);
    src_y = src_y(valid);
    if numel(src_t) < 2, continue; end

    [src_t,ia] = unique(src_t,'stable');
    src_y = src_y(ia);
    [src_t,order] = sort(src_t);
    src_y = src_y(order);

    if isempty(Tref)
        Tref = src_t;
        Y = nan(numel(Tref),numel(cfg.subjects));
    end

    yi = interp1(src_t,src_y,Tref,'linear',NaN);
    Y(:,s) = yi; %#ok<AGROW>
    plot(ax,Tref,yi,'Color',[0.80 0.80 0.80],'LineWidth',0.6);
end

if ~isempty(Y)
    mu = mean(Y,2,'omitnan');
    plot(ax,Tref,mu,'k','LineWidth',2.2);

    trace_names = matlab.lang.makeValidName(strcat('sub_',cfg.subjects));
    trace_table = array2table([Tref Y], ...
        'VariableNames',[{'TimeMin'},trace_names]);
    writetable(trace_table,fullfile(out_dir,'rv_normalized_traces_wide.csv'));

    group_table = table(Tref,mu, ...
        std(Y,0,2,'omitnan')./sqrt(sum(isfinite(Y),2)), ...
        sum(isfinite(Y),2), ...
        'VariableNames',{'TimeMin','Mean_scaled_dRR','SEM','N'});
    writetable(group_table,fullfile(out_dir,'rv_normalized_group_mean.csv'));
end

xline(ax,0,'k:','LineWidth',0.8);
xline(ax,10,'k:','LineWidth',0.8);
xline(ax,20,'k:','LineWidth',0.8);
title(ax,'RV','FontWeight','bold');
xlabel(ax,'Time (min)');
ylabel(ax,'scaled dR/R');
xlim(ax,[-10 30]);
set(ax,'FontName','Arial','FontSize',10,'Layer','top');

exportgraphics(fig,fullfile(out_dir,'RV_10min_traces.pdf'), ...
    'ContentType','vector');
close(fig);

fprintf('Extended Data Fig. 6c summary complete.\n');

summary = struct( ...
    'subject_summary',T_subject, ...
    'group_summary',T_group, ...
    'positive_auc',T_positive, ...
    'intervals',intervals, ...
    'labels',{interval_labels});
end

function [m,A,Aneg,Apos] = analyse_interval(t,y,range,carry_tail)
mask = t >= range(1) & t <= range(2) & isfinite(t) & isfinite(y);
if nnz(mask) < 2
    [m,A,Aneg,Apos] = deal(NaN);
    return;
end

tx = t(mask);
yx = y(mask);
[tx,ia] = unique(tx,'stable');
yx = yx(ia);
[tx,order] = sort(tx);
yx = yx(order);

if carry_tail && tx(end) < range(2)
    dt = median(diff(tx),'omitnan');
    if isfinite(dt) && dt > 0
        tail_t = (tx(end)+dt:dt:range(2))';
        if ~isempty(tail_t)
            y_mean = mean(yx,'omitnan');
            tx = [tx;tail_t];
            yx = [yx;repmat(y_mean,numel(tail_t),1)];
        end
    end
end

m = mean(yx,'omitnan');
segment_auc = 0.5.*(yx(1:end-1)+yx(2:end)).*diff(tx);
A = sum(segment_auc,'omitnan');
Aneg = sum(min(segment_auc,0),'omitnan');
Apos = sum(max(segment_auc,0),'omitnan');
end
