%% BATCH_PROCESSING_FIG3D_HAB3
clear; clc;

paths = dlight_paths('fig3d');
addpath(paths.script_root);
if isfolder(paths.tdt_sdk_root), addpath(genpath(paths.tdt_sdk_root)); end

subjects = {'032417','032418','032419','032421','032422','032423','032426','035031','035032'};
process_only = subjects;  % e.g. {'032417'} for a validation run

for i = 1:numel(subjects)
    animal = subjects{i};
    if ~isempty(process_only) && ~any(strcmp(process_only,animal)), continue; end

    cfg = fig3d_config(animal);
    raw_folder = fullfile(paths.raw_root,'hab3',animal);

    fprintf('\n=== Fig. 3d | hab3 | %s ===\n',animal);
    fprintf('Raw folder: %s\n',raw_folder);

    if ~isfolder(raw_folder)
        fprintf(2,'[ERROR] %s: raw folder not found.\n',animal);
        continue;
    end

    try
        process_fig3d_hab3_dlight( ...
            'day','hab3', ...
            'raw_folder',raw_folder, ...
            'subject',animal, ...
            'timestamps',cfg.hab3.timestamps, ...
            'output_root',paths.output_root, ...
            'raw_start_s',cfg.raw_start_s, ...
            'lowpass_hz',cfg.lowpass_hz, ...
            'target_fs',cfg.target_fs, ...
            'raw_finish_note',cfg.hab3.raw_finish_note, ...
            'bleach_smoothing_method',cfg.hab3.bleach_smoothing_method, ...
            'bleach_smoothing_window',cfg.hab3.bleach_smoothing_window, ...
            'bleach_fit_start_idx',cfg.hab3.bleach_fit_start_idx, ...
            'bleach_fit_end_trim_idx',cfg.hab3.bleach_fit_end_trim_idx, ...
            'start_point_405',cfg.hab3.start_point_405, ...
            'start_point_465',cfg.hab3.start_point_465, ...
            'baseline_fit_smoothing_method',cfg.hab3.baseline_fit_smoothing_method, ...
            'baseline_fit_smoothing_window',cfg.hab3.baseline_fit_smoothing_window, ...
            'baseline_fit_start_offset',cfg.hab3.baseline_fit_start_offset, ...
            'save_mat',true, ...
            'save_figures',false);
        fprintf('[OK] %s complete.\n',animal);
    catch ME
        fprintf(2,'[ERROR] %s: %s\n',animal,ME.message);
    end
end

fprintf('\nFig. 3d hab3 batch complete.\n');
