%% BATCH_PROCESSING_FIG2BD
% Process habituation and VG/RG/RV recordings used for Fig. 2b-d.

clear; clc;

paths = dlight_paths('fig2bd');
addpath(paths.script_root);
if isfolder(paths.tdt_sdk_root), addpath(genpath(paths.tdt_sdk_root)); end

subjects = fig2bd_subjects();
conditions = fig2bd_conditions();
process_only_animals = subjects;
process_only_conditions = conditions;

%% Habituation recordings
for i = 1:numel(subjects)
    animal = subjects{i};
    if ~isempty(process_only_animals) && ...
            ~any(strcmp(process_only_animals,animal))
        continue;
    end

    cfg = fig2bd_config(animal,'hab3');
    raw_folder = fullfile(paths.raw_root,'hab3',animal);
    fprintf('\n=== Fig. 2b-d | hab3 | %s ===\n',animal);

    if ~isfolder(raw_folder)
        fprintf(2,'[ERROR] Raw folder not found: %s\n',raw_folder);
        continue;
    end

    try
        process_fig2bd_dlight( ...
            'mode','hab3', ...
            'condition','hab3', ...
            'raw_folder',raw_folder, ...
            'subject',animal, ...
            'output_root',paths.fig2bd_output_root, ...
            'signal_stream',cfg.signal_stream, ...
            'reference_stream',cfg.reference_stream, ...
            'raw_start_s',cfg.raw_start_s, ...
            'raw_finish_note',cfg.hab3.raw_finish_note, ...
            'lowpass_hz',cfg.hab3.lowpass_hz, ...
            'target_fs',cfg.target_fs, ...
            'bleach_smoothing_window',cfg.hab3.bleach_smoothing_window, ...
            'hab3_fit_trim_start',cfg.hab3.fit_trim_start, ...
            'hab3_fit_trim_end',cfg.hab3.fit_trim_end, ...
            'start_point_405',cfg.hab3.start_point_405, ...
            'start_point_465',cfg.hab3.start_point_465, ...
            'timestamps',cfg.hab3.timestamps, ...
            'sync_epoc',cfg.test.sync_epoc, ...
            'fpx_time_range',cfg.test.fpx_time_range);
    catch ME
        report_error('hab3',animal,ME);
    end
end

%% VG, RG and RV recordings
for c = 1:numel(conditions)
    condition = conditions{c};
    if strcmpi(condition,'hab3') || ...
            (~isempty(process_only_conditions) && ...
            ~any(strcmp(process_only_conditions,condition)))
        continue;
    end

    for i = 1:numel(subjects)
        animal = subjects{i};
        if ~isempty(process_only_animals) && ...
                ~any(strcmp(process_only_animals,animal))
            continue;
        end

        cfg = fig2bd_config(animal,condition);
        raw_folder = fullfile(paths.raw_root,condition,animal);
        hab3_file = fullfile(paths.fig2bd_output_root,'hab3',animal, ...
            ['hab3_' animal '_processed.mat']);
        fprintf('\n=== Fig. 2b-d | %s | %s ===\n',condition,animal);

        if ~isfolder(raw_folder) || ~isfile(hab3_file)
            fprintf(2,'[ERROR] Missing raw folder or hab3 output.\n');
            continue;
        end

        try
            process_fig2bd_dlight( ...
                'mode','test', ...
                'condition',condition, ...
                'raw_folder',raw_folder, ...
                'subject',animal, ...
                'hab3_fit_file',hab3_file, ...
                'output_root',paths.fig2bd_output_root, ...
                'signal_stream',cfg.signal_stream, ...
                'reference_stream',cfg.reference_stream, ...
                'raw_start_s',cfg.raw_start_s, ...
                'raw_finish_note',cfg.test.raw_finish_note, ...
                'lowpass_hz',cfg.test.lowpass_hz, ...
                'target_fs',cfg.test.target_fs, ...
                'baseline_smoothing_window',cfg.test.baseline_fit_smoothing_window, ...
                'use_bleach_correction',cfg.test.use_bleach_correction, ...
                'timestamps',cfg.test.timestamps, ...
                'sync_epoc',cfg.test.sync_epoc, ...
                'fpx_time_range',cfg.test.fpx_time_range);
        catch ME
            report_error(condition,animal,ME);
        end
    end
end

fprintf('\nFig. 2b-d preprocessing complete.\n');

function report_error(condition,animal,ME)
fprintf(2,'[ERROR] %s | %s: %s\n',condition,animal,ME.message);
for k = 1:numel(ME.stack)
    fprintf(2,'  %s (line %d)\n',ME.stack(k).name,ME.stack(k).line);
end
end
