%% SUMMARY_BASAL_FIG3J
% Group and per-animal summary of Fig. 3j GR basal fluorescence.

clear; clc;

paths = dlight_paths('fig3j');
cfg = fig3j_config('055619');
subjects = gr_rv_subjects();

summarize_basal_gr_rv( ...
    'group',cfg.group, ...
    'figure',cfg.figure, ...
    'figure_label',cfg.figure_label, ...
    'subjects',subjects, ...
    'basal_root',paths.gr_basal_root, ...
    'summary_root',paths.gr_summary_root, ...
    'summary_xlim',cfg.summary_xlim, ...
    'summary_boundaries',cfg.summary_boundaries, ...
    'save_png',cfg.save_summary_png);
