%% SUMMARY_BASAL_EXTFIG6A
% Group and per-animal summary of Extended Data Fig. 6a RV fluorescence.

clear; clc;

paths = dlight_paths('extfig6a');
cfg = extfig6a_config('055619');
subjects = gr_rv_subjects();

summarize_basal_gr_rv( ...
    'group',cfg.group, ...
    'figure',cfg.figure, ...
    'figure_label',cfg.figure_label, ...
    'subjects',subjects, ...
    'basal_root',paths.rv_basal_root, ...
    'summary_root',paths.rv_summary_root, ...
    'summary_xlim',cfg.summary_xlim, ...
    'summary_boundaries',cfg.summary_boundaries, ...
    'save_png',cfg.save_summary_png);
