%% SUMMARY_BASAL_FIG2BD
% Run the Fig. 2b-d table, source-data and trace summary.

clear; clc;

paths = dlight_paths('fig2bd');
summarize_fig2bd( ...
    'subjects',fig2bd_subjects(), ...
    'conditions',fig2bd_conditions(), ...
    'basal_root',paths.fig2bd_basal_root, ...
    'summary_root',paths.fig2bd_summary_root);
